#!/usr/bin/env python

"""
Synopsis vowels input-name

Generate all variations of a base name as a string, that are generated by
substituting alternative vowels in every place that the name containes a 
vowel.

Return a list of strings with all the variations.
"""

from sys import argv

VOWELS = "aeiou"
vowel_index = []
name_variations = []
input_name = argv[1]

for i in range( len( input_name ) ):
    if VOWELS.__contains__( input_name[i] ):
        #print VOWELS.__contains__( input_name[i] )
        vowel_index.append(i)
#print vowel_index
#print len(vowel_index)
#if len(vowel_index) > 0:

name_variations.append(input_name)

for i in VOWELS:
    for j in VOWELS:
        if input_name.replace(i,j) != input_name:
            if name_variations.__contains__( input_name.replace(i,j) ) == False:
                name_variations.append( input_name.replace(i,j) )
            #print input_name.replace(i, j)

print name_variations
